platform :ios, '9.0'

target 'SwiftyCompanion' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SwiftyCompanion
  pod 'Alamofire'
  pod 'SwiftyJSON'

end
